name: Hispaniam Fidelis
title: Hispaniam Fidelis | Patriotas sin excusas
description: Una plataforma para contribuir en proyectos que mejoren España
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Principal
    url: /
  - title: Sobre HF
    url: /about
  - title: Contacto
    url: /contact
email: hispaniamfidelis@proton.me
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
